name: Push Event Workflow

on: push 

jobs:
  unit-testing:
    runs-on: ubuntu-latest 
    
    steps:
    - name : Checkout code
      uses : actions/checkout@v2
      
    #- name : Install Packages 
    #  run : pip install unittest
      
    - name : Run tests 
      run : python -m unittest  tests/integration/test-solvers.py 
